### ISSUE TITLE
Paper for the `WODL` version

### ISSUE THREAD

**Issue by dyhBUPT** [lzzppp/SR-Track#1]
Hi, thanks for your excellent work. And I've read your AAAI 2024 paper.

I want to know if the `WODL` version of SR-Track has a paper? Or do you plan to write a new paper for it?

**Comment by lzzppp** [comment]
Hello! This is the technical part of another paper of ours titled: "DoveDB: A Declarative and Low-Latency Video Database".

**Comment by dyhBUPT** [comment]
Thank you!
