### ISSUE TITLE
BNN-Based Noise Estimation

### ISSUE THREAD

**Issue by Kev1nDeng** [lzzppp/SR-Track#2]
Hi, I've read your 2024 aaai paper, and I'm wondering where's the BNN-Based Noise Estimation implemented in your code? I didn't find it in branch 2, and great work btw!

**Comment by lzzppp** [comment]
Hello!
Thank you very much for your interest in this part! There is still follow-up work to be done on the optimization of the BNN part, and we will update this project later. In addition, the current algorithm performance of the project is close to the open source code.
---- Replied Message ----
***@***.***>Date12/23/2024 ***@***.***>***@***.***>Subject[lzzppp/SR-Track] BNN-Based Noise Estimation (Issue #2)
Hi, I've read your 2024 aaai paper, and I'm wondering where's the BNN-Based Noise Estimation implemented in your code? I didn't find it in branch 2, and great work btw!

**Comment by Kev1nDeng** [comment]
Oh I see! Thanks for your reply!
